blueprint:
  name: tado - Auto HOME/AWAY
  description: Set Climate mode when someone enters/left Home - v1.0.1
  domain: automation
  source_url: https://github.com/kimeikato/hass-blueprints/blob/main/tado/tado_auto_preset.yaml
  input:
    climate:
      name: Climate
      selector:
        entity:
          domain: climate
          multiple: true
    zone:
      name: Zone
      selector:
        entity:
          domain: zone

mode: restart

trigger:
  - platform: state
    entity_id: !input zone
    to: "0"
  - platform: state
    entity_id: !input zone
    from: "0"

condition: []

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input zone
            above: 0
        sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: auto
            target:
              entity_id: !input climate
          - service: climate.set_preset_mode
            data:
              preset_mode: home
            target:
              entity_id: !input climate
      - conditions:
          - condition: numeric_state
            entity_id: !input zone
            below: 1
        sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: auto
            target:
              entity_id: !input climate
          - service: climate.set_preset_mode
            data:
              preset_mode: away
            target:
              entity_id: !input climate