blueprint:
  name: tado - Open Window
  description: Set Climate mode when window open/closes - v2.0.0
  domain: automation
  source_url: https://github.com/kimeikato/hass-blueprints/blob/main/tado_open_window.yaml
  input:
    window:
      name: Window
      selector:
        entity:
          device_class: window
    climate:
      name: Climate
      selector:
        entity:
          domain: climate

mode: restart

trigger:
  - platform: state
    entity_id:
      - !input window
    to: "on"
  - platform: state
    entity_id:
      - !input window
    from: "on"

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input window
            state: "on"
        sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: "off"
            target:
              entity_id: !input climate
      - conditions:
          - condition: state
            entity_id: !input window
            state: "off"
        sequence:
          - service: tado.set_climate_timer
            data:
              temperature: 10
              time_period: "00:10:00"
            target:
              entity_id: !input climate